# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Demo Slot
description: Nonton Streaming Bokep Thailand
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nontonbokep.pages.dev"

permalink: /blog/:title

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

include: ["posts.json"]

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

SITE_KEY:
API_KEY: AIzaSyDUIngXq4cj7XMx6RSOEiNj-aWSjhk0FZ4
AUTH_DOMAIN: lalajo-bokep.firebaseapp.com
DATABASE_URL: https://lalajo-bokep-default-rtdb.asia-southeast1.firebasedatabase.app
PROJECT_ID: lalajo-bokep
STORAGE_BUCKET: lalajo-bokep.firebasestorage.app
SENDER_ID: 243575604544
APP_ID: 1:243575604544:web:5c161c68407947a0b8e6a5
MEASUREMENT_ID: G-QMRXFDSLDN
